### ISSUE TITLE
getting  lua errors 

### ISSUE THREAD

**Issue by raykai** [JocysCom/TextToSpeech#24]
16x [string "JocysCom_StopButtonFrame:OnEnter"]:2: attempt to index global 'JocysCom_SaveButton' (a nil value)
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

Locals:
self = JocysCom_StopButtonFrame {
 0 = <userdata>
}
motion = true
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'JocysCom_SaveButton' (a nil value)"

**Comment by VJocys** [comment]
Thank you. Updated Addon to 2.2.86 (2016-12-14) and Monitor to 2.4.8 (2016-12-14) versions.
I hope, I fixed the problem with Addon... by removing "JocysCom_SaveButton:Show();" action (on entering "JocysCom_StopButtonFrame") in XML file, because "JocysCom_SaveButton" was removed in previous version already.
